# Minimun config
title: "LAGO Data Management Plan"
remote_theme: pmarsceill/just-the-docs
# Color scheme supports "light" (default) and "dark"
color_scheme: "light"
# logo: "/images/lago.png"
baseurl: "/DMP" # the subpath of your site, e.g. /blog
# url: "https://lagoproject.github.io/DMP" # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty
# exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile", "docs/tests/"]

# Regression tests
# By default, the pages in /docs/tests are excluded when the ste is built.
# To include them, comment-out the relevant line above.
# Uncommenting the following line doesn't work - see https://github.com/jekyll/jekyll/issues/4791
# include: ["docs/tests/"]

# 
#
# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
#
#
# Aux links for the upper right navigation
aux_links:
  "Just the Docs on GitHub":
    - "//github.com/pmarsceill/just-the-docs"
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false
#
#
# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
# Supports true (default) or false
heading_anchors: true
#
# Footer content 
# appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2020, The LAGO Collaboration. Distributed by an <a href=\"https://github.com/lagoproject/DMP/tree/master/LICENSE\">CC BY-NC-SA 4.0</a>"
# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/lagoproject/DPM" # the github URL for your repo
gh_edit_branch: "develop" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
#
#
# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
# ga_tracking: UA-5555555-55
# ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)
#
#
# Define Jekyll collections
# collections:
  # Define a collection named "docs", its documents reside in the "_docs" directory
  #docs:
  #  permalink: "/:collection/:path/"
  #  output: true
# just_the_docs:
  # Define which collections are used in just-the-docs
  #collections:
  #  # Reference the "docs" collection
  #  docs:
  #    # Give the collection a name
  #    name: Documentation
  #    # Exclude the collection from the navigation
  #    # Supports true or false (default)
  #    nav_exclude: false
  #    # Exclude the collection from the search
  #    # Supports true or false (default)
  #    search_exclude: false


  

